spring:
  application:
    name: Veo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        sslmode: require
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc: 
          time-zone: SYSTEM
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: 604800000
logging:
  level:
    com:
      winnerezy:
        Veo: DEBUG
server:
  forward-headers-strategy: framework
  port: 8080
